name: Thought Stream
# This workflow is triggered on pushes to the repository.
on:
  push
  # push:
  #   branches:
  #     - actions
  #   # file paths to consider in the event. Optional; defaults to all.
  #   paths:
  #     - "content/stream-of-consciousness/*"

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      name: "Hello World"
      description: "Greet someone and record the time"
      inputs:
        who-to-greet: # id of input
          description: "Who to greet"
          required: true
          default: "World"
      outputs:
        time: # id of output
          description: "The time we greeted you"
      runs:
        using: "node12"
        main: "greet.js"
  # thought:
  #   name: New Thought
  #   runs-on: ubuntu-latest
  #   steps:
  #     # - uses: ./.github/actions/new-thought
  #     - run: ./stream.js
