name: Thought Stream
# This workflow is triggered on pushes to the repository.
on:
  push
  # push:
  #   branches:
  #     - actions
  #   # file paths to consider in the event. Optional; defaults to all.
  #   paths:
  #     - "content/stream-of-consciousness/*"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Hello world action step
        id: hello
        uses: ./.github/actions/hello-world-javascript-action
        with:
          who-to-greet: "Mona the Octocat"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
  thoughts:
    name: Thoughts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: ./.github/actions/new-thought
